# Generated by Django 3.0.5 on 2020-06-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_auto_20200605_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
