# Generated by Django 3.0.5 on 2020-06-13 15:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0014_billingadress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAdress',
            new_name='BillingAddress',
        ),
    ]
