# Generated by Django 3.0.5 on 2020-07-05 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0021_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='full_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='password',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='v_name',
            new_name='shop_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.Vendor'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='seller',
            field=models.OneToOneField(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='store_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
